### ISSUE TITLE
analyza sw

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#1]
Vyskusat kniznicu OpenCV v Pythone.

**Comment by gajdosech2** [comment]
do branche analyza_sw som pridal prototyp

**Comment by janocko5** [comment]
Stiahol som prototyp a spustil u seba pekná práca.

**Comment by gajdosech2** [comment]
Pozrite novy prototyp. Ak nemate pripojenu webkameru, pouzije sa video, ktore som nahral. Naviac viete uz aj do obrazu kreslit stvorce, ktore zatial nemaju ziadnu funkciu, no je to na ukazku ze ako asi budeme robit tie oblasti zaujmu.

Kod som rozdelil do tried a konfiguracia uz je teraz prepojena s rezimom behu, cize funguje napriklad vyber rozlisenia.
