### ISSUE TITLE
navrh implementacie 

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#13]
Vytvoril som sablonu dokumentu - navrhu, ktory odovzdavame do 13.11.:
https://docs.google.com/document/d/1M-JsyP2SArCXriOUFJFMwYsltRbIqYgewfDrIXUWvOs/edit?usp=sharing. Kazdy s odkazom by mal mat prava na upravu. 

Zatial som len vytvoril jednotlive kapitoly a obsah, pricom som nazvy prekladal z anglickeho originalu, ktory je v materialoch (http://dai.fmph.uniba.sk/courses/tvorbaIS/tis/new.html) v stati 4.3. Dokument budeme postupne spolocne naplnat, tak ako predtym Katalog Poziadaviek. Nazvy jednotlivych sekcii sa samozrejme mozu menit podla vhodnosti a niektore z nich mozno nebudeme potrebovat, ine pridame.

**Comment by gajdosech2** [comment]
Po konzultacii 9.11 som prekopal obsah, nazvy aj rozdelenie na kapitoly. Stale vychadzame z osnovy na stranke, no je to prisposobene pre nas system a pre potreby zadania, ktore mame do 13.11. V obsahu som k jednotlivym polozkam napisal komentare, co maju cca obsahovat a kto ich ma na starosti. Taktiez je tam pri kazdej polozke v hranatych zatvorkach napisane, s ktorym bodom zadania to suvisi (A,B,C,D).

Finalnu verziu navrhu nemusime odovzdat do 13.11., no chceme ju mat vtedy a hlavne do piatku 16.11 (cize dalsieho stretnutia) v nejakej rozumnej forme aj s diagramami.

**Comment by kyselica12** [comment]
doplnena cast 5.2 pre opencv a numpy

**Comment by kyselica12** [comment]
https://drive.google.com/file/d/1eZld0ppeIQa1kGxUJJVV08BQFXG7jbjZ/view?usp=sharing link na predbezny class diagram ktory je generovany z triek commitnutych do master branchu

**Comment by kyselica12** [comment]
Triedy commitnute su zatial ako "kostra" systemu. Budu este doplnene. Boli vytvorene na generovanie prvotneho class diagramu, ktory zatial nie je kompletny, kvoli nejasnostiam ktore este prediskutujeme na stretnuti

**Comment by gajdosech2** [comment]
@kyselica12 skus pozriet este nejake ine nastroje na generovanie triedneho diagramu, na googli sa spomina napriklad **pyreverse**

**Comment by gajdosech2** [comment]
na stretnuti 16.11 sme sa dohodli, ze v priebehu buduceho tyzdna bude dokonceny dokument navrhu a poslany na schvalenie petrovicovi. Idealne teda ak my sme to tak utorok/stredu mali.

Dovtedy v skratke potrebujeme:

1. ja trocha prepisem subezne procesy
2. @janocko5  prerobi komponenty diagram a popis k nemu
3. @kyselica12  trocha upravi cast o perzistentnych udajoch, doriesi triedny diagram a napise k nemu popis. Pripadne mu s popisom pomozeme.

**Comment by kyselica12** [comment]
doplnený class diagram ako aj popis k nemu

**Comment by gajdosech2** [comment]
Na stretnuti 23.11. sme si rozdelili povinnosti na nasledujuci tyzden:

- Vsetci: prediskutovat rozhrania medzi modulmi, ktore budeme mat jednotlivo na starosti (GUI - Lukas, Sprava suborov - Miro, Hlavny beh - Dano), aby sme vedeli co si +- budu medzi sebou posielat, ako budu komunikovat
-  Lukas: zacat s implementaciou GUI, poslat dokonceny navrh
- Dano: Dopisat do navrhu cast s algoritmom rozpoznania
- Miroslav: Zacat s pripravou testovacich scenarov. Cize natacanie na webkamere, spracovanie, popis zaberov, ich ucel, aku poziadavku z katalogu testuju... Zo zadania:
> Na Githube je dokument s testovacími scenármi - ktorý vznikne podľa Katalógu požiadaviek. Jeden scenár môže testovať aj viacero požiadaviek, ale každá požiadavka z katalógu musí byť kompletne pokrytá v nejakom testovacom scenári.

Idem este vytvorit prislusne issues a pouzatvarat dokoncene
