### ISSUE TITLE
UML state alebo UML sequence diagram 

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#14]
K navrhu do 13.11. potrebujeme mat aj jeden z dvojice UML state a UML sequence diagram. 

_Sekvencnym diagramom_ by sme v nasom pripade mohli dobre popisat scenar zachytenia pohybu v oblasti zaujmu s doplnkovymi moznostami (Opt) spustenia zvukoveho alarmu a nahravania zaznamu. 

_Stavovym diagramom_ by sa dali dobre zachytit stavy, ktorymi prechadza cely system, teda najma prechod medzi rezimom konfiguracie a behu. Avsak v materialoch k predmetu je napisane:

> ...Tento typ diagramu je možné použiť, ak za entitu vezmeme samotný informačný systém, prípadne jeho používateľské rozhranie, ale v tomto príklade a aj v príkladoch, ktoré nás počas tímového projektu a písomných testov budú zaujímať, budú modelované stavy inej entity. V tomto prípade ide o entitu voľby... (viac na http://dai.fmph.uniba.sk/courses/tvorbaIS/tis/new.html#uml-priklad)

@pavelpetrovic znamena to teda, ze nemozeme modelovat priamo stavy samotneho systemu, ale nejakej inej entity? Ak tomu spravne rozumiem, modelovali by sme teda napriklad stavy entity "Oblast zaujmu" ktora prechadza z nejakeho stavu sledovana, do stavu zalarmovana a podobne? Vdaka za odpoved.

___

Ktory z tychto dvoch diagramov by ste navrhovali vypracovat? Po vybere som ochotny sa tejto ulohy zhostit...

**Comment by kyselica12** [comment]
Ja navrhujem sekvencny tam v nasom pripade lepsie ukazeme chod systemu

**Comment by pavelpetrovic** [comment]
idealne je spravit aj sekvencny aj stavovy. uprednostnujem inu entitu ako "system".

**Comment by gajdosech2** [comment]
Skusil som vytvorit sekvencny diagram, popisujuci scenar "Kontrola pohybu v oblasti zaujmu". Co poviete?
[Sekvenčný Diagram.pdf](https://github.com/TIS2018-FMFI/visionlab-fotopasca/files/2526654/Sekvencny.Diagram.pdf)

**Comment by pavelpetrovic** [comment]
na prvy pohlad velmi pekne. detaily pochopim asi az osobne.
