### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by janocko5** [TIS2018-FMFI/visionlab-fotopasca#18]
Caute posielám prvú verziu UML component diagramu..

https://drive.google.com/file/d/14qMMQO70WL7Orzrzuppe7CyfosKIDRUS/view

**Comment by pavelpetrovic** [comment]
teším sa z pokroku, ďakujem.
pre istotu len pripomínam, že krúžok označuje nejaký poskytovaný interfejs, na ktorý sa "ručička" pripája - využíva ho. krúžky prosím kreslite len na konci úsečiek, nie pod nimi.
dúfam, že každý nakreslený dokument viete vysvetliť - čo je jeho úlohou - a zachytíte to aj v texte návrhu.

**Comment by janocko5** [comment]
Upravil som tie krúžky a snažil som sa dať trošku viac rovnejšie čiary...

https://drive.google.com/file/d/14qMMQO70WL7Orzrzuppe7CyfosKIDRUS/view

**Comment by pavelpetrovic** [comment]
Len na prvy pohlad: ak by ste prehodili tvorbu zaznamu a casozber, tak by sa vam spojenia nemuseli vobec krizit. Inak ak by sa na takyto captavy obrazok pozrel inzinier, asi by sa dlho smial.
To  je problem nakreslit presne vodorovne usecky?
Naco ma spracovanie obrazu na spodku take dlhe vemeno, ked jeho polozky koncia na tom istom mieste ako susedna konfiguracia, ktora je ovela kratsia?

**Comment by janocko5** [comment]
Upravil som to.

https://drive.google.com/file/d/14qMMQO70WL7Orzrzuppe7CyfosKIDRUS/view?usp=sharing

**Comment by janocko5** [comment]
Nový upravený diagram, prosím pozrite sa na to a dajte feedback.

https://drive.google.com/file/d/1QD98xB6tqaPyaSV2KgFAiUGYSaTx0Ja6/view

**Comment by pavelpetrovic** [comment]
na prvy pohlad:
"gulicky" (interfejsy) by mali byt blizko pri moduloch.
mohli by byt aj pomenovane, ale nie je to nutne.

**Comment by gajdosech2** [comment]
@janocko5 pridal komponentny diagram v tomto stave aj do dokumentu (https://github.com/TIS2018-FMFI/visionlab-fotopasca/issues/13), spolocne s popisom. Predstavuje to zakladny prvok casti **D.** z aktualneho zadania. Moje poznamky:

1. Z technickeho hladiska by trebalo diagram preusporiadat, aby lepsie pasoval do vysledneho dokumentu. Idealne ho teda orientovat na vysku, aby pokryl cely list A4, prinajhorsom ho tam vlozit "na lezato". Taktiez je tam v pomerne zlej kvalite, tazko citatelny a rozmazany. Da sa s tym nieco urobit? Osobne som sekvencny diagram a navrh UI skusal exportovat v roznych rozliseniach .PNG, az dokym som nedosiahol optimalnu ostrost.

2. No a teraz k slovnemu popisu v dokumente. V prvom rade po sebe treba citat, kedze tam bolo znova vela gramatickych chyb, ktore ale boli vyslovene z nepozornosti (chybajuce slova/pismena).

3. Stylistika a gramatika by ale v tomto pripade boli ten najmensi problem. Horsie je, ze je popis po obsahovej stranke nedostatocny a hlavne nepresny:

     - V popise modulu GUI je asi 80% textu o roznych nastaveniach, ktore v nasom systeme su. To vsetko su ale veci, ktore patria k popisu modulu konfiguracia a nemaju s GUI prakticky nic spolocne. To je modul, ktory sa stara cisto o vizualne rozhranie celeho systemu. Namiesto toho, _co_ sa v nasom systeme vsetko da nastavit, tu teda treba naopak popisat _ako_ to bude vyzerat, respektive vyzera, kedze uz mame prototyp a aj navrh UI. Teda, ze su tam veci ako tlacidla a posuvne bezce. Samozrejme vystizne, k veci.

     - Nazov "Ukladač snímkov" pre velky komponent zahrnujuci podkomponenty rezim behu, kamera loop a riadenie snimania mi pride nevhodny. Nechapem kde sa to ani takto poplietlo, kedze este na stretnuti v piatok sme to volali inak. Prave cely tento velky komponent mal niest nazov "Režim behu" a obsahovat podkomponenty kamera loop, riadenie snimania a v prvom rade komponent Kontrola, ktory sa bude starat o kontrolu pohybu v jednotlivych oblastiach pohybu. Cele toto ved nema ziaden suvis s ukladanim snimkov, o to sa predsa stara ulozisko. Tym padom nesedi ani slovny popis. Musel si si to asi nejako dopliest, lebo pokial si spravne pamatam, tak aj v tom nacrte z piatku sme to mali inak.

     - Popis komponentu Úložisko - "Tento modul bude obsahovať a uchovávať spracované dáta...". Hovorili sme si k tomuto predsa v piatok. Komponenty v systeme maju predstavovat nejake ucelene softverove casti. Ako sa teda ma chapat veta, ze tento modul/komponent bude OBSAHOVAT spracovane data? Tie budu predsa ulozene na disku, a to s komponentom nema nic spolocne. Tento komponent sa cisto stara o zapisovanie/citanie suborov na disku, a teda aj popis sa ma niest v duchu "Tento modul a jeho podkomponenty sa budu starat o uchovavanie a spracovanie dat..." atd.

Bude asi potrebne si to zajtra cele znova prejst. Myslel som si, ze na piatkovom stretnuti to bolo dostatocne prekonzultovane aj s pomocou @pavelpetrovic, ale asi nie.

**Comment by janocko5** [comment]
Zmeny som zapracoval dávnejšie, boli okey môžme uzavrieť toto issues ??

**Comment by gajdosech2** [comment]
Ano, zatvaram.
