### ISSUE TITLE
Implementacia GUI

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#21]
Tuto cast systemu budem mat na starosti ja, zacnem s postupnou implementaciou.

**Comment by gajdosech2** [comment]
[gui.zip](https://github.com/TIS2018-FMFI/visionlab-fotopasca/files/2612447/gui.zip)

Prva verzia GUI, staci spustit GUI.py.

Este tam chybaju nastavenia, musim uhladit kod, povolit vytvaranie viacerych ROI a napojit to do celeho systemu, hlavne aby to pracovalo s komponentami Ulozisko a Konfiguracia. Cize zatial len taka alfa verzia na ukazku.

**Comment by gajdosech2** [comment]
[gui2.zip](https://github.com/TIS2018-FMFI/visionlab-fotopasca/files/2613615/gui2.zip)

Dalsia verzia GUI s nasledujucimi zmenami:
- sprehladnil som kod
- tlacidla a oblasti zaujmu som oddelil do samostatnych tried
- triedy rozdelil do packages
- teraz uz je mozne vytvarat viacero oblasti zaujmu (tahanim mysi) a tie ostavaju ulozene. Navyse sa daju aj vyznacit dvojklikom a nasledne vymazat, pricom platia podmienky z katalogu poziadaviek ([ukazka.zip](https://github.com/TIS2018-FMFI/visionlab-fotopasca/files/2613618/ukazka.zip))
- niektore premenne som aj otypoval, no zatial nie vsetky

Nadalej ale este chyba napojenie s komponentami Ulozisko a Konfiguracia, to chcem s vami osobne prediskutovat... Taktiez niektore polozky v konfiguracii mam po slovensky, no rezim behu ma potom texty po anglicky, lebo mi openCV robilo problem s diakritikou... Dame to teda cele po anglicky? 
___

Navyse vam chcem oznamit, ze tento piatok 30.11. nebudem na stretnuti, budem totizto odcestovany. Praca za tento tyzden z mojej strany teda je:
- doklepnutie katalogu
- praca na tomto komponente GUI

Snad moja absencia nebude vadit, o vsetkom ma informujte, vdaka.

**Comment by kyselica12** [comment]
no nechajme to slovenske radsej ked uz aj predtym dokument mame slovensky to by bol taky mizmaz mat jedno take druhe take

**Comment by gajdosech2** [comment]
Hej len tym padom je cudne, ze v rezime behu je "Config" a informacia "Terminate the app with Q", lenze ked tam tam "Pre ukončenie stlač Q" tak sa tie "č" zle zobrazia... zle kodovanie. Pozriem, ci sa to niekde v OpenCV kniznici neda nastavit, len som chcel vediet vas nazor SK vs AJ. Ja som osobne tiez za to, aby to bolo po slovensky :)

**Comment by pavelpetrovic** [comment]
poprosil by som potom kod, ktory uz bude pouzity v projekte nahravat do prislusnej branch git-u a casom mergovat do mastra - hned ako je nieco ucelene a nie prikladat v zipoch do issues.

**Comment by gajdosech2** [comment]
@pavelpetrovic vytvoril som novu branch "gui" a kod som do nej nahral.

**Comment by gajdosech2** [comment]
Do konfiguracneho okna som pridal vsetky nastavenia z katalogu poziadaviek tak, aby sa zhodovalo s navrhom UI. Na ukazku posielam aj screenshoty z Windowsu a macOS:

![mac](https://user-images.githubusercontent.com/36670639/49227026-6ce96f00-f3e8-11e8-824c-466d62832f26.jpg)
![win](https://user-images.githubusercontent.com/36670639/49227027-6ce96f00-f3e8-11e8-98a3-1b29f675563f.jpg)

Take basic, ale myslim si ze prehladne a je tam vsetko, co treba.
