### ISSUE TITLE
Testovacie scenare

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#22]
Do  27. 11. 2017 potrebujeme mat pripravene testovacie scenare, zadanie:
> Na Githube je dokument s testovacími scenármi - ktorý vznikne podľa Katalógu požiadaviek. Jeden scenár môže testovať aj viacero požiadaviek, ale každá požiadavka z katalógu musí byť kompletne pokrytá v nejakom testovacom scenári.

K dispozicii mame 2 webkamery, takze ich mozeme pripravovat ja a Miro.

Dokument: https://goo.gl/fVYZHC

**Comment by janocko5** [comment]
Doplnené testovácie scenáre skúste pozrieť, a dajte feedback.

**Comment by janocko5** [comment]
Tu je dokument:

https://docs.google.com/document/d/1nl4xNOo44GNGPdloQS0KfQt_-NHJk9R0miBCEYNszhk/edit

**Comment by janocko5** [comment]
Videa k jednotlivím scenárom nahrám na google disk a linky pridám do dokumentu .

**Comment by pavelpetrovic** [comment]
pekne, vdaka. niekto iny by teraz mohol prejst katalog poziadaviek a skontrolovat, ci je kazda poziadavka pokryta v nejakom scenari.

**Comment by gajdosech2** [comment]
Testovacie scenare by mali sediet s poziadavkami, Miro to spravil takmer jedna k jednej. Kazdopadne celkom nerozumiem, preco su vsetky videa dole hlavou a hlavne preco maju velky, cierny okraj? A taktiez scenare, ktore testuju doplnkove scenare B by som presunul na koniec zoznamu a nejako ich vyznacil.

**Comment by janocko5** [comment]
V dokumente som rozdelil scenáre na 1.1 Povinné, 1.2 Doplnkové, 1.3 Kvalitatívne požiadavky a 1.4 Požiadavky rozhrania v priebehu dna natočím nové videa v požadovanej kvalite a tým hneď otestujem ukladač.

https://docs.google.com/document/d/1nl4xNOo44GNGPdloQS0KfQt_-NHJk9R0miBCEYNszhk/edit#heading=h.x1pn3ndy4nqx
