### ISSUE TITLE
Implementacia

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#27]
6.12.2018 sme na stretnuti zacali spajat jednotlive komponenty a vytvorili tak prvu funkcnu verziu finalneho programu. Do 23. 12. 2018 by sme chceli mat vacsinu programu hotovu, pricom cez Vianoce uz budeme len vyladovat/vylepsovat.

**Comment by gajdosech2** [comment]
Buduci tyzden budeme mat znova stretnutie, pricom dovtedy:

- **Miro** implementuje komponent Saver, teda ukladac snimkov/videi na disk. Ten bude nasledne zapracovany do celeho systemu.
- **Dano** bude dalej pracovat na hlavnom algoritme kontroly obrazu a na dalsich triedach komponentu Process.
- **Lukas** doplni tlacidlo na nahravanie a posuvny bezec na nastavovanie citlivosti oblasti zaujmu do GUI a zapracuje triedu Alarmovac, ktora je tiez sucastou komponentu GUI, kedze je to nejaka odozva uzivatelovi.

Taktiez by bolo fajn, ak by sme dovtedy mali pripravene nejake finalne testovacie scenare, nech to vieme rovno aj vyskusat.

**Comment by janocko5** [comment]
Kedže je všetko hotové každý spravil svoju časť toto issue sa môže uzavrieť.
