### ISSUE TITLE
Suhrnne PDF

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#30]
Zo zaverecneho zadania:

> Zdrojový kód je na Githube vrátane jedného kompletného PDF súboru, ktorý obsahuje aj katalóg požiadaviek aj návrh, pričom je aktualizovaná tak, aby bola v súlade s odovzdaným kódom. 

Na tento ucel som znova vytvoril novy google document: https://docs.google.com/document/d/1SefQ4sfBiif2y2O87d3x4kKONNG-KO8DJ90-OMKmMdM/edit?usp=sharing. 

Do neho som skopiroval mierne upraveny Katalog, Navrh aj Scenare. Okrem drobnych textovych uprav som zmenil hlavne strukturu a nazvy kapitol, aby sedeli do suhrnneho dokumentu. Pri tej prilezitosti som aj dokladne pozrel testovacie scenare od Mira a upravil nejake detaily.

Do dokumentu potrebujeme spolocne dopisat uzivatelsku prirucku, pricom to ma na starosti najma @janocko5. Ja a @kyselica12 dokoncime implementaciu a dokumentaciu kodu. Sucastou technickej dokumentacie bude aj vygenerovane .html s dokumentaciou (vid. #29).

**Comment by janocko5** [comment]
Užívateľská príručka dopísana, prosím skontrolujte či je to v pohode. Dík.

**Comment by gajdosech2** [comment]
Skontroloval som prirucku, nejake veci pomenil a doplnil. Myslim si, ze by to teraz malo byt okej.
