### ISSUE TITLE
pridat dokonceny katalog poziadaviek

### ISSUE THREAD

**Issue by gajdosech2** [TIS2018-FMFI/visionlab-fotopasca#6]

**Comment by gajdosech2** [comment]
Do branchu Dokumenty som pridal aktualne finalny katalog poziadaviek. Issue ale nechavam zatial otvoreny, na zapracovanie poznamok od zadavatela. 

K dokumentu sa uz vyjadril. So vsetkym suhlasil, mal iba dve poznamky - v stati 2.4 vseobecne obmedzenia sme mali napisane, ze kamera nemoze byt na prilis tmavom alebo svetlom mieste. V skutocnosti je ale podstatne aby sledovana oblast zaujmu nebola prilis tmava alebo svetla, na umiestneni samotnej kamery teda vlastne nezalezi. Tuto drobnost som uz zapracoval do dokumentu.

No a druha poznamka: 
> Zvazit umiestnenie adresara timelapse v adresary program data, alebo inom, do ktoreho vie zapisovat uzivatel aj bez prav administratora. (**A - RB01 - Časozber:** Ak užívateľ aktivoval funkciu časozberu v konfigurácii, tak sú snímky v nastavenom intervale automaticky ukladané na disk počas celého behu (do automaticky vytvorenej zložky ‘timelapse’ vedľa aplikácie, jednotlivé snímky majú názov s aktuálnym dátumom a časom). Informácia o tom, či je táto funkcia zapnutá je v dolnej lište.

Toto som zatial nechal tak, co si o tom myslite?

**Comment by janocko5** [comment]
Pozrel som v dokumente zapracovanú časť 2.4 podľa mňa je v pohode, môže to tak ostať. 
Umiestnenie adresára v timelapse , počkajme na Dana on je vedúci implementácie navrhujem nech sa on na to vyjadrí.

**Comment by pavelpetrovic** [comment]
Mne by sa samozrejme pacilo, aby sa to dalo nastavit v konfiguracnom subore. 
Defaultny config by bol nastaveny tak, aby sa subory ukladali do ProgramData, ale
pouzivatel by to mohol zmenit na ine miesto. Tyka sa isto tyka vsetkych ukladanych
suborov, nielen casozber. ProgramData ma zmysel hlavne vtedy, keby sa aplikacia
do systemu nahravala cez instalacny program administratorom. Ak sa len niekde
rozzipuje, tak potom je to jedno. V principe slusna aplikacia sa na Windows z bezpecnostnych
dovodov instaluje, aby ju nemohol hociaky virus prepisat... Ale to zalezi na tom, ako
daleko to chcete s tymto programom dotiahnut. V MSVS by malo byt pomerne priamociare
vygenerovat instalacny program. Uz v polovici devatdesiatych rokov to tak bolo. :-)

**Comment by gajdosech2** [comment]
Do branche Dokumenty som pridal odkaz na katalog poziadaviek v Google Docs. Zapracoval som tam poziadavky, o ktorych sme sa bavili na stretnuti 26.10.2018. Taktiez som poslal tuto najnovsiu verziu zadavatelovi a poprosil ho o formalny suhlas.

**Comment by gajdosech2** [comment]
Zadavatel napisal svoj suhlas. Preposlal som ho mailom na @pavelpetrovic a sem prikladám screenshot:
![screenshot 2018-10-29 at 15 19 39](https://user-images.githubusercontent.com/36670639/47655868-396bb880-db8e-11e8-87e6-5ba3a5858299.png)
